### ISSUE TITLE
tomcat8 logback1.1.8 print traeid error

### ISSUE THREAD

**Issue by dongchaoforever** [wu-sheng/sky-walking#104]
The error log:

14:48:13,787 |-ERROR in ch.qos.logback.core.ConsoleAppender[stdout] - Appender [stdout] failed to append. java.lang.ClassNotFoundException: WebappClassLoader
  context: manager
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@12e61fe6
 load interceptor class:com.a.eye.skywalking.toolkit.log.logback.v1.x.PrintTraceIdInterceptor failure.
	at java.lang.ClassNotFoundException: WebappClassLoader
  context: manager
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@12e61fe6
 load interceptor class:com.a.eye.skywalking.toolkit.log.logback.v1.x.PrintTraceIdInterceptor failure.
	at 	at com.a.eye.skywalking.plugin.interceptor.loader.InterceptorInstanceLoader.load(InterceptorInstanceLoader.java:56)
	at 	at com.a.eye.skywalking.plugin.interceptor.enhance.ClassInstanceMethodsInterceptor.intercept(ClassInstanceMethodsInterceptor.java:51)
	at 	at com.a.eye.skywalking.toolkit.log.logback.v1.x.LogbackPatternConverter.convert(LogbackPatternConverter.java)
	at 	at com.a.eye.skywalking.toolkit.log.logback.v1.x.LogbackPatternConverter.convert(LogbackPatternConverter.java:9)
	at 	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:36)
	at 	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:114)
	at 	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:141)
	at 	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:1)
	at 	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:130)
	at 	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:187)
	at 	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
	at 	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:100)
	at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at 	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at 	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at 	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at 	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at 	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at 	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.info(SLF4JLocationAwareLog.java:155)
	at 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:305)
	at 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at 	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at 	at com.a.eye.skywalking.plugin.interceptor.loader.InterceptorInstanceLoader.loadBinary(InterceptorInstanceLoader.java:116)
	at 	at com.a.eye.skywalking.plugin.interceptor.loader.InterceptorInstanceLoader.load(InterceptorInstanceLoader.java:48)
	at 	... 30 common frames omitted #

**Comment by wu-sheng** [comment]
`com.a.eye.skywalking.toolkit.activation.log.logback.v1.x.LogbackPatternConverterActivation.getInstanceMethodsInterceptPoints` did not return the right interceptor class name.

- 2.2-2017
```java
return "com.a.eye.skywalking.toolkit.log.logback.v1.x.PrintTraceIdInterceptor";
```

- actual class name
```java
return "com.a.eye.skywalking.toolkit.activation.log.logback.v1.x.PrintTraceIdInterceptor";
```

**Comment by wu-sheng** [comment]
Fixed, ready to release.
