### ISSUE TITLE
2.0-2016 docke-compose error log 

### ISSUE THREAD

**Issue by bill23-kim** [wu-sheng/sky-walking#135]
When I run it using the 2.0-2016 tag docker-compose.yml, the following error log appears periodically.

~~~
skywalking-storage_1      | org.elasticsearch.client.transport.TransportClientNodesService -1361033 [elasticsearch[_client_][generic][T#3]] DEBUG null - failed to connect to node [{#transport#-1}{tPZnOLnSTxCW9_P8N3d5Sw}{127.0.0.1}{127.0.0.1:35000}], removed from nodes list
skywalking-storage_1      | org.elasticsearch.transport.ConnectTransportException: [][127.0.0.1:35000] connect_timeout[30s]
skywalking-storage_1      | 	at org.elasticsearch.transport.netty4.Netty4Transport.connectToChannelsLight(Netty4Transport.java:340) ~[transport-netty4-client-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:400) ~[elasticsearch-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at org.elasticsearch.transport.TcpTransport.connectToNodeLight(TcpTransport.java:372) ~[elasticsearch-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:297) ~[elasticsearch-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:378) [elasticsearch-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:324) [elasticsearch-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at org.elasticsearch.client.transport.TransportClientNodesService$ScheduledNodeSampler.run(TransportClientNodesService.java:357) [elasticsearch-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:451) [elasticsearch-5.0.1.jar:5.0.1]
skywalking-storage_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
skywalking-storage_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
skywalking-storage_1      | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
skywalking-storage_1      | Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:35000
skywalking-storage_1      | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_111]
skywalking-storage_1      | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_111]
skywalking-storage_1      | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
skywalking-storage_1      | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
skywalking-storage_1      | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:627) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
skywalking-storage_1      | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
skywalking-storage_1      | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
skywalking-storage_1      | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
skywalking-storage_1      | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
skywalking-storage_1      | 	... 1 more
~~~

How can i solve it?

**Comment by wu-sheng** [comment]
We double check the docker-compose. Your log is true, but it is harmless. Because when 2.x, we did not check the Elasticsearch status, just try to connect. Sorry.

We have improved in 3.0. By the whole new architecture, this should never happen again.

**Comment by bill23-kim** [comment]
Is that error log not affecting the skywalking system? Even though i have installed agent in my web application, nothing appears on web ui.

**Comment by wu-sheng** [comment]
Yes, it did not affect. Here is my double check result.

![97e17f9466d4b16d775b49523a916900](https://cloud.githubusercontent.com/assets/5441976/24950432/9a2acb96-1fa3-11e7-8312-c402246e66c3.jpg)

As you got nothing on the UI, you need understand these things first.
- The UI show the trace only when you have a trace id.
- The two ways you got the trace id in 2.x are,
  1. Error alarm mails. Exceptions or slow transactions occur in your application.
  1. Use the application-log-toolkit, then the traceid is in your application log. Like [log4j2-toolkit](https://github.com/wu-sheng/sky-walking/wiki/sky-walking-application-toolkit-log4j-2.x)

I think these two ways are both not easy enough, so we give you the new feature about query traces without any conditions in 3.0. : ) Hope everyone love this feature.

**Comment by bill23-kim** [comment]
It would be better to wait for 3.0. Thank you for your reply.

**Comment by wu-sheng** [comment]
Even 3.0 had released, but we still have docker issue, which about uploading failure....

So if you are still interested in 3.0, I recommend you follow this deploy document: https://github.com/wu-sheng/sky-walking/wiki/3.0-Deploy-cluster, which is also easy enough to start a server.

**Comment by bill23-kim** [comment]
@wu-sheng 
thank you. I have already installed it and tried to apply the demo application, which seems to work well.

**Comment by wu-sheng** [comment]
@bill23-kim Thanks for any feedback, suggestion or proposal, even contribution. You are always welcome
