### ISSUE TITLE
Deploy  collector , collector.log show NoNodeAvailableException.

### ISSUE THREAD

**Issue by WallC0902** [wu-sheng/sky-walking#140]
deploy collector ，use ES 5.3, and then `collector.log` show
```
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{hxQnEow4SJugAHGyEUtnyg}{192.168.3.240}{192.168.3.240:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:344)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:242)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:356)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1226)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at com.a.eye.skywalking.collector.worker.storage.AbstractIndex.isExists(AbstractIndex.java:92)
	at com.a.eye.skywalking.collector.worker.storage.IndexCreator.create(IndexCreator.java:23)
	at com.a.eye.skywalking.collector.worker.CollectorBootStartUp.main(CollectorBootStartUp.java:23)
```
	
	skywalking-server-log4j2.log stop with
```
2017-04-14 17:09:15,582 - com.a.eye.skywalking.collector.CollectorSystem -1631 [main] INFO  [] - loadLocalProviders provider name: com.a.eye.skywalking.collector.worker.globaltrace.persistence.GlobalTraceSearchWithGlobalId$Factory
	2017-04-14 17:09:15,582 - com.a.eye.skywalking.collector.CollectorSystem -1631 [main] INFO  [] - loadLocalProviders provider name: com.a.eye.skywalking.collector.worker.span.persistence.SpanSearchWithId$Factory
	2017-04-14 17:09:15,585 - com.a.eye.skywalking.collector.CollectorSystem -1634 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,624 - com.a.eye.skywalking.collector.CollectorSystem -1673 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,637 - com.a.eye.skywalking.collector.CollectorSystem -1686 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,652 - com.a.eye.skywalking.collector.CollectorSystem -1701 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,666 - com.a.eye.skywalking.collector.CollectorSystem -1715 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,685 - com.a.eye.skywalking.collector.CollectorSystem -1734 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,699 - com.a.eye.skywalking.collector.CollectorSystem -1748 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,711 - com.a.eye.skywalking.collector.CollectorSystem -1760 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,728 - com.a.eye.skywalking.collector.CollectorSystem -1777 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,745 - com.a.eye.skywalking.collector.CollectorSystem -1794 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,765 - com.a.eye.skywalking.collector.CollectorSystem -1814 [main] INFO  [] - create {10} worker using java service loader
	2017-04-14 17:09:15,976 - org.elasticsearch.plugins.PluginsService -2025 [main] INFO  [] - no modules loaded
	2017-04-14 17:09:15,978 - org.elasticsearch.plugins.PluginsService -2027 [main] INFO  [] - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
	2017-04-14 17:09:15,978 - org.elasticsearch.plugins.PluginsService -2027 [main] INFO  [] - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
	2017-04-14 17:09:15,978 - org.elasticsearch.plugins.PluginsService -2027 [main] INFO  [] - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
	2017-04-14 17:09:15,978 - org.elasticsearch.plugins.PluginsService -2027 [main] INFO  [] - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
	2017-04-14 17:09:15,978 - org.elasticsearch.plugins.PluginsService -2027 [main] INFO  [] - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
	2017-04-14 17:09:16,991 - com.a.eye.skywalking.collector.worker.storage.EsClient -3040 [main] INFO  [] - es nodes: 192.168.3.240:9300
	2017-04-14 17:09:47,212 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33261 [main] INFO  [] - index name: segment_idx
	2017-04-14 17:09:47,212 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33261 [main] INFO  [] - index name: segment_cost_idx
	2017-04-14 17:09:47,213 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33262 [main] INFO  [] - index name: segment_exp_idx
	2017-04-14 17:09:47,213 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33262 [main] INFO  [] - index name: global_trace_idx
	2017-04-14 17:09:47,214 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33263 [main] INFO  [] - index name: node_comp_idx
	2017-04-14 17:09:47,214 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33263 [main] INFO  [] - index name: node_mapping_idx
	2017-04-14 17:09:47,222 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33271 [main] INFO  [] - index name: node_ref_idx
	2017-04-14 17:09:47,222 - com.a.eye.skywalking.collector.worker.storage.IndexCreator -33271 [main] INFO  [] - index name: node_ref_res_sum_idx
```
	
	
	collector was in 192.168.3.122，ES was in 192.168.3.240。
	collector.config：
```
        cluster.current.hostname=192.168.3.122
	cluster.current.port=11800

	cluster.current.roles=WorkersListener

	cluster.seed_nodes=192.168.3.122:11800

	es.cluster.name=CollectorDBCluster
	es.cluster.transport.sniffer=true

	es.cluster.nodes=192.168.3.240:9300

	es.index.initialize.mode=auto
	es.index.shards.number=2
	es.index.replicas.number=0

	http.hostname=127.0.0.1
	http.port=12800
	http.contextPath=/

	cache.analysis.size=1024
	cache.persistence.size=1024

	WorkerNum.Node.NodeCompAgg.Value=10
	WorkerNum.Node.NodeMappingDayAgg.Value=10
```
	
	elasticsearch.yml：
	
```
        network.host: 0.0.0.0
	cluster.name: CollectorDBCluster
	node.name: node1
	thread_pool.bulk.queue_size: 1000
```

**Comment by wu-sheng** [comment]
@WallC0902 What is your status? now. As we provided new collector with more log configs, can you give us some updates?

**Comment by WallC0902** [comment]
Now everything is fine, with the new collector and in other loom reinstall the elasticsearch. It seems because the old environment docker generated virtual network card, resulting in this problem

**Comment by wu-sheng** [comment]
@WallC0902  So, we can close this, now?

**Comment by wu-sheng** [comment]
Closing

**Comment by WallC0902** [comment]
yes，thanks
