### ISSUE TITLE
Failed to start collector container

### ISSUE THREAD

**Issue by ascrutae** [wu-sheng/sky-walking#246]
Error log:
```
skywalking-collector_1  | Exception in thread "main" java.net.UnknownHostException: es-server: Name or service not known
skywalking-collector_1  | 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
skywalking-collector_1  | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
skywalking-collector_1  | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
skywalking-collector_1  | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
skywalking-collector_1  | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
skywalking-collector_1  | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
skywalking-collector_1  | 	at java.net.InetAddress.getByName(InetAddress.java:1076)
skywalking-collector_1  | 	at org.skywalking.apm.collector.worker.storage.EsClient.boot(EsClient.java:42)
skywalking-collector_1  | 	at org.skywalking.apm.collector.worker.CollectorBootStartUp.main(CollectorBootStartUp.java:22)
```

**Comment by wu-sheng** [comment]
Fixed, closing.
