### ISSUE TITLE
Failed to access Injectable class

### ISSUE THREAD

**Issue by ascrutae** [wu-sheng/sky-walking#258]
`org.skywalking.apm.plugin.dubbo.DubboInterceptor$1` is anonymous inner class for `Injectable`. Is that byte-buddy support access anonymous inner class in the interceptor method ?
Here is the error log
```
java.lang.IllegalAccessError: tried to access class org.skywalking.apm.plugin.dubbo.DubboInterceptor$1 from class org.skywalking.apm.plugin.dubbo.DubboInterceptor
	at org.skywalking.apm.plugin.dubbo.DubboInterceptor.beforeMethod(DubboInterceptor.java:60)
	at org.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:62)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
```

**Comment by wu-sheng** [comment]
It is triggered by ClassLoader scope. Fixed by new API style.
