### ISSUE TITLE
skywalking-3.1-2017追踪web工程日志,使用tomcat8遇到了log4j pattern解析异常，不能解析[%T]

### ISSUE THREAD

**Issue by guorj217** [wu-sheng/sky-walking#309]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.1-2017追

### What version of your OS?
x86_64 GNU/Linux

### What version of your JRE?
1.8.0_131

### What company or project?
java web

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
tomcat 版本:apache-tomcat-8.0.39 apache-tomcat-8.5.9
jdk: 1.8.0_131
web 工程: web.xml version="3.1"
web 工程 log4j:
...layout=org.skywalking.apm.toolkit.log.log4j.v1.x.TraceIdPatternLayout
....ConversionPattern=%d{yyyy-MM-dd HH:mm:ss SSS} %-5p [%T] [%x] [%t]%C{1}.%M(%L) - %m%n
工程 lib目录下引入: sky-walking.config skywalking-agent.jar apm-toolkit-log4j-1.x-3.1-2017.jar apm-toolkit-opentracing-3.1-2017.jar
tomcat: catalina.sh 下增加
CATALINA_OPTS="$CATALINA_OPTS -javaagent:/home/username/tool/data/gatewayMicroShop/WEB-INF/lib/skywalking-agent.jar"; export CATALINA_OPTS
启动 tomcat : 异常栈信息
21-Jul-2017 11:42:23.014 信息 [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.39
21-Jul-2017 11:42:30.027 信息 [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this
logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN Failed to set property [conversionPattern] to value "%d{yyyy-MM-dd HH:mm:ss SSS} %-5p [%T] [%x] [%t]%C{1}.%M(%L) - %m%n".
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:245)
at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:204)
at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:169)
at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:805)
at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
at org.apache.log4j.LogManager.(LogManager.java:127)
at org.apache.log4j.Logger.getLogger(Logger.java:104)
at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:289)
at org.apache.commons.logging.impl.Log4JLogger.(Log4JLogger.java:109)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:1116)
at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:914)
at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:604)
at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:336)
at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:310)
at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
at org.springframework.beans.CachedIntrospectionResults.(CachedIntrospectionResults.java:62)
at org.springframework.web.util.IntrospectorCleanupListener.contextInitialized(IntrospectorCleanupListener.java:75)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
at org.skywalking.apm.toolkit.log.log4j.v1.x.TraceIdPatternParser.finalizeConverter(TraceIdPatternParser.java:18)
at org.apache.log4j.helpers.PatternParser.parse(PatternParser.java:186)
at org.apache.log4j.PatternLayout.setConversionPattern(PatternLayout.java:450)
... 39 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.skywalking.apm.toolkit.log.log4j.v1.x.TraceIdPatternConverter.(TraceIdPatternConverter.java)
... 42 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:114)
... 47 more
Caused by: java.lang.IllegalArgumentException: Can not set static org.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassInstanceMethodsInterceptor field org.skywalking.apm.toolkit.log
.log4j.v1.x.TraceIdPatternConverter.delegate$kmvn8e1 to org.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassInstanceMethodsInterceptor
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at sun.reflect.UnsafeStaticObjectFieldAccessorImpl.set(UnsafeStaticObjectFieldAccessorImpl.java:79)
at java.lang.reflect.Field.set(Field.java:764)
at org.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:105)
at org.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:180)
at org.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:180)
at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:2430)
... 52 more
log4j:WARN Failed to set property [conversionPattern] to value "%d{yyyy-MM-dd HH:mm:ss SSS} %-5p [%T] [%x] [%t]%C{1}.%M(%L) - %m%n".
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:245)
at org.apache.log4j.config.PropertySetter.setProperty(PropertySetter.java:204)
at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:169)
at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:805)
at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
at org.apache.log4j.LogManager.(LogManager.java:127)
at org.apache.log4j.Logger.getLogger(Logger.java:104)
at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:28

类比:使用 tomcat 6 和tomcat 7 没有问题，可以正常的使用 skywalking ,且生成traceId例如 Trace.1500605395032.-1092464309.23686.44.2
请大牛指点迷津，感激感谢！

**Comment by wu-sheng** [comment]
@guorj217 请提供一下log4j和tomcat的具体版本号。谢谢。

**Comment by guorj217** [comment]
@wu-sheng  您好 Tomcat/8.0.39   log4j-1.2.17

**Comment by ascrutae** [comment]
@guorj217 我在本地使用Tomcat/8.0.39 log4j-1.2.17没办法复现你的问题，能否提供你的demo？

**Comment by guorj217** [comment]
@ascrutae  demo http://pan.baidu.com/s/1jHToPRC   密码 qq您啦

**Comment by ascrutae** [comment]
@guorj217 这个问题是由于部署探针方式导致的，探针不应该放在classes目录下。而应该有一个单独的目录存放。close.

**Comment by wu-sheng** [comment]
@guorj217 放在Tomcat CLASSPATH相关路径下，会由于不同版本的Tomcat ClassLoader机制不同，可能造成探针被其他classloader加载，造成各种不可预知问题，请知晓。
