### ISSUE TITLE
use example segments json post error

### ISSUE THREAD

**Issue by swift1911** [wu-sheng/sky-walking#314]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.1

### What version of your OS?
os x 10.12.5

### What version of your JRE?
1.8.0_112-b16

### What company or project?
collector

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

curl -H Content-Type: application/json ; charset=UTF-8 -XPOST http://localhost:12800/segments -d [
    {
        "ts": "Segment.1490097253214.-866187727.57515.1.1",
        "st": 1490097253198,
        "et": 0,
        "rs": [
            {
                "ts": "parent_trace_0",
                "si": 1,
                "ac": "REMOTE_APP",
                "ph": "10.2.3.16:8080"
            },
            {
                "ts": "parent_trace_1",
                "si": 5,
                "ac": "REMOTE_APP",
                "ph": "10.2.3.16:8080"
            },
            {
                "ts": "parent_trace_2",
                "si": 5,
                "ac": "REMOTE_APP",
                "ph": "10.2.3.16:8080"
            }
        ],
        "ss": [
            {
                "si": 1,
                "ps": -1,
                "st": 1490097253228,
                "et": 0,
                "on": "/serviceA",
                "ts": {
                    "span.layer": "http"
                },
                "tb": {},
                "ti": {},
                "lo": []
            },
            {
                "si": 2,
                "ps": 1,
                "st": 1490097253230,
                "et": 0,
                "on": "/db/sql",
                "ts": {
                    "span.layer": "db"
                },
                "tb": {},
                "ti": {},
                "lo": [
                    {
                        "tm": 1490097253234,
                        "fi": {
                            "stack": "java.lang.NullPointerException
	at com.a.eye.skywalking.trace.TraceSegmentTestCase.testSerialize(TraceSegmentTestCase.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
",
                            "error.kind": "java.lang.NullPointerException",
                            "event": "error"
                        }
                    }
                ]
            }
        ],
        "ac": "billing_app",
        "gt": [
            "Trace.1490097253227.-866187727.57515.1.2"
        ]
    }
]
result:
{"isSuccess":false,"reason":"For input string: \"[\n\""}%

**Comment by swift1911** [comment]
elasticsearch无错误日志

**Comment by wu-sheng** [comment]
为什么使用`curl`来发送JSON呢？是有自己的探针的，在对接后端么？

可参考：https://github.com/wu-sheng/sky-walking/wiki/3.0-Collector-TraceSegment-in-JSON-format。这个里面涉及很多JSON格式化和特殊字符方面的要求。

请反馈一下使用的具体场景，谢谢。

**Comment by wu-sheng** [comment]
最准备的segment格式化，可参考segment使用GSON格式化的相关代码：
https://github.com/wu-sheng/sky-walking/blob/v3.1/apm-commons/apm-trace/src/main/java/org/skywalking/apm/trace/TraceSegment.java

**Comment by swift1911** [comment]
我们有自己开发的探针，想用自己开发的探针对接skywalking

**Comment by wu-sheng** [comment]
从你目前的报错来看，是因为json在传递时，\n没有正确的序列化，和GSON的反序列化不符。

推荐你可以参考服务端的testCase:

https://github.com/wu-sheng/sky-walking/blob/v3.1/apm-collector/apm-collector-worker/src/test/java/org/skywalking/apm/collector/worker/segment/SegmentRealPost.java

对应的模拟报文代码：
* 模拟代码
https://github.com/wu-sheng/sky-walking/blob/v3.1/apm-collector/apm-collector-worker/src/test/java/org/skywalking/apm/collector/worker/segment/mock/SegmentMock.java
* json
https://github.com/wu-sheng/sky-walking/blob/v3.1/apm-collector/apm-collector-worker/src/test/resources/json/segment/post/normal/portal-service.json

另外，你们是Java探针还是其他语言的？

**Comment by swift1911** [comment]
我们用的是Golang

**Comment by wu-sheng** [comment]
你可以使用刚才发给你的json进行一下测试。

**Comment by swift1911** [comment]
问题解决了，replace掉空格就好了

**Comment by wu-sheng** [comment]
好的，有问题保持沟通，如果你们的golang探针接入后工作正常，欢迎分享截图和案例。对于多语言的接入，我们十分欢迎。
