### ISSUE TITLE
log4j2 activation failure, when target LogEventPatternConverter's subclass

### ISSUE THREAD

**Issue by wu-sheng** [wu-sheng/sky-walking#71]
When log4j2 activation target TraceIdConverter:
```java
public class TraceIdConverter extends LogEventPatternConverter
```

TraceIdConverter initialize failure, when log4j2 start up when Tomcat8 start up. But it can't be replicated in https://github.com/ascrutae/skywalking-log4j2-test. 

Recheck on branch: https://github.com/wu-sheng/sky-walking/tree/feature/log4j2-weaver-failure-recheck.

```
11-Dec-2016 19:34:26.890 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /Users/xin/Programs/apache-tomcat-8.5.4/webapps/manager
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:549)
	at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:602)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:386)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:171)
	at org.apache.logging.log4j.core.layout.PatternLayout.createSerializer(PatternLayout.java:124)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:111)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:58)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:494)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:405)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:882)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:874)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:498)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:227)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:239)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:530)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:603)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:620)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:226)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
	at com.a.eye.skywalking.docker.test.DockerEnvTestServlet.<init>(DockerEnvTestServlet.java:17)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
```

**Comment by wu-sheng** [comment]
Bug should be reproduced in https://github.com/ascrutae/skywalking-log4j2-test, but not for now.

**Comment by wu-sheng** [comment]
Closing this, since this is not important right now.
